<link rel="stylesheet" href="{{ url('/layouts_landing') }}/css/bootstrap.min.css" type="text/css">
<link rel="stylesheet" href="{{ url('/layouts_landing') }}/css/font-awesome.min.css" type="text/css">
<link rel="stylesheet" href="{{ url('/layouts_landing') }}/css/elegant-icons.css" type="text/css">
<link rel="stylesheet" href="{{ url('/layouts_landing') }}/css/flaticon.css" type="text/css">
<link rel="stylesheet" href="{{ url('/layouts_landing') }}/css/owl.carousel.min.css" type="text/css">
<link rel="stylesheet" href="{{ url('/layouts_landing') }}/css/nice-select.css" type="text/css">
<link rel="stylesheet" href="{{ url('/layouts_landing') }}/css/jquery-ui.min.css" type="text/css">
<link rel="stylesheet" href="{{ url('/layouts_landing') }}/css/magnific-popup.css" type="text/css">
<link rel="stylesheet" href="{{ url('/layouts_landing') }}/css/slicknav.min.css" type="text/css">
<link rel="stylesheet" href="{{ url('/layouts_landing') }}/css/style.css" type="text/css">
